apiVersion: v1
kind: ResourceQuota
metadata:
  name: job-hunting-quota
  namespace: job-hunting
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 4Gi
    limits.cpu: "4"
    limits.memory: 8Gi
    pods: "20"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: video-analysis-quota
  namespace: video-analysis
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 4Gi
    limits.cpu: "4"
    limits.memory: 8Gi
    pods: "10"
    count/jobs.batch: "20"
